"""Tests for the generate-pr-description.py script.

This file and its associated tests flow down via a SYNC action from the jebel-quant/rhiza repository
(https://github.com/jebel-quant/rhiza).

The script generates PR descriptions for rhiza sync operations.
"""

import shutil
import subprocess

# Get shell path once at module level
PYTHON = shutil.which("python3") or "/usr/bin/python3"
GIT = shutil.which("git") or "/usr/bin/git"


def test_pr_description_no_changes(git_repo, root):
    """Test PR description generation with no staged changes."""
    script = git_repo / ".rhiza" / "scripts" / "generate-pr-description.py"

    # Copy the script to the test repo
    shutil.copy(
        root / ".rhiza" / "scripts" / "generate-pr-description.py",
        script
    )
    script.chmod(0o755)

    # Create .rhiza/template.yml
    template_file = git_repo / ".rhiza" / "template.yml"
    template_file.parent.mkdir(parents=True, exist_ok=True)
    with open(template_file, "w") as f:
        f.write('template-repository: "jebel-quant/rhiza"\n')
        f.write('template-branch: "main"\n')

    # Commit the script and template
    subprocess.run([GIT, "add", "."], cwd=git_repo, check=True)
    subprocess.run([GIT, "commit", "-m", "Add PR description script"], cwd=git_repo, check=True)

    # Run the script with no staged changes
    result = subprocess.run(
        [PYTHON, str(script)],
        cwd=git_repo,
        capture_output=True,
        text=True
    )

    assert result.returncode == 0
    assert "Template Synchronization" in result.stdout
    assert "No changes detected" in result.stdout


def test_pr_description_with_changes(git_repo, root):
    """Test PR description generation with staged changes."""
    script = git_repo / ".rhiza" / "scripts" / "generate-pr-description.py"

    # Copy the script to the test repo
    shutil.copy(
        root / ".rhiza" / "scripts" / "generate-pr-description.py",
        script
    )
    script.chmod(0o755)

    # Create .rhiza/template.yml
    template_file = git_repo / ".rhiza" / "template.yml"
    template_file.parent.mkdir(parents=True, exist_ok=True)
    with open(template_file, "w") as f:
        f.write('template-repository: "jebel-quant/rhiza"\n')
        f.write('template-branch: "main"\n')

    # Commit the script and template
    subprocess.run([GIT, "add", "."], cwd=git_repo, check=True)
    subprocess.run([GIT, "commit", "-m", "Add PR description script"], cwd=git_repo, check=True)

    # Create some test changes
    # Add a new workflow file
    workflows_dir = git_repo / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)
    workflow_file = workflows_dir / "test.yml"
    with open(workflow_file, "w") as f:
        f.write("name: Test\n")

    # Modify an existing file
    with open(git_repo / "pyproject.toml", "a") as f:
        f.write("\n# Updated\n")

    # Add a new script
    new_script = git_repo / ".rhiza" / "scripts" / "test.sh"
    with open(new_script, "w") as f:
        f.write("#!/bin/sh\necho test\n")

    # Stage the changes
    subprocess.run([GIT, "add", "."], cwd=git_repo, check=True)

    # Run the script
    result = subprocess.run(
        [PYTHON, str(script)],
        cwd=git_repo,
        capture_output=True,
        text=True
    )

    assert result.returncode == 0
    assert "Template Synchronization" in result.stdout
    assert "files added" in result.stdout
    assert "files modified" in result.stdout
    assert "GitHub Actions Workflows" in result.stdout or "Configuration Files" in result.stdout
    assert "jebel-quant/rhiza" in result.stdout
    assert "Generated by" in result.stdout


def test_pr_description_output_file(git_repo, root):
    """Test PR description generation to output file."""
    script = git_repo / ".rhiza" / "scripts" / "generate-pr-description.py"

    # Copy the script to the test repo
    shutil.copy(
        root / ".rhiza" / "scripts" / "generate-pr-description.py",
        script
    )
    script.chmod(0o755)

    # Create .rhiza/template.yml
    template_file = git_repo / ".rhiza" / "template.yml"
    template_file.parent.mkdir(parents=True, exist_ok=True)
    with open(template_file, "w") as f:
        f.write('template-repository: "jebel-quant/rhiza"\n')
        f.write('template-branch: "main"\n')

    # Commit the script and template
    subprocess.run([GIT, "add", "."], cwd=git_repo, check=True)
    subprocess.run([GIT, "commit", "-m", "Add PR description script"], cwd=git_repo, check=True)

    # Create a test change
    test_file = git_repo / "test.txt"
    test_file.write_text("test content")

    # Stage the change
    subprocess.run([GIT, "add", "."], cwd=git_repo, check=True)

    # Run the script with output file
    output_file = git_repo / "pr-description.md"
    result = subprocess.run(
        [PYTHON, str(script), "--output", str(output_file)],
        cwd=git_repo,
        capture_output=True,
        text=True
    )

    assert result.returncode == 0
    assert output_file.exists()
    content = output_file.read_text()
    assert "Template Synchronization" in content
    assert "files added" in content


def test_pr_description_categorizes_files(git_repo, root):
    """Test that PR description categorizes files correctly."""
    script = git_repo / ".rhiza" / "scripts" / "generate-pr-description.py"

    # Copy the script to the test repo
    shutil.copy(
        root / ".rhiza" / "scripts" / "generate-pr-description.py",
        script
    )
    script.chmod(0o755)

    # Create .rhiza/template.yml
    template_file = git_repo / ".rhiza" / "template.yml"
    template_file.parent.mkdir(parents=True, exist_ok=True)
    with open(template_file, "w") as f:
        f.write('template-repository: "jebel-quant/rhiza"\n')
        f.write('template-branch: "main"\n')

    # Commit the script and template
    subprocess.run([GIT, "add", "."], cwd=git_repo, check=True)
    subprocess.run([GIT, "commit", "-m", "Add PR description script"], cwd=git_repo, check=True)

    # Create files in different categories
    # Workflow
    workflows_dir = git_repo / ".github" / "workflows"
    workflows_dir.mkdir(parents=True, exist_ok=True)
    (workflows_dir / "ci.yml").write_text("name: CI\n")

    # Documentation
    (git_repo / "README.md").write_text("# Test\n")

    # Tests
    tests_dir = git_repo / "tests"
    tests_dir.mkdir(parents=True, exist_ok=True)
    (tests_dir / "test_example.py").write_text("def test(): pass\n")

    # Rhiza script
    scripts_dir = git_repo / ".rhiza" / "scripts"
    scripts_dir.mkdir(parents=True, exist_ok=True)
    (scripts_dir / "test.sh").write_text("#!/bin/sh\n")

    # Stage all changes
    subprocess.run([GIT, "add", "."], cwd=git_repo, check=True)

    # Run the script
    result = subprocess.run(
        [PYTHON, str(script)],
        cwd=git_repo,
        capture_output=True,
        text=True
    )

    assert result.returncode == 0
    assert "GitHub Actions Workflows" in result.stdout
    assert "Documentation" in result.stdout
    assert "Tests" in result.stdout
    assert "Rhiza Scripts" in result.stdout
