"""Lock model for Rhiza configuration."""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from rhiza.models._git_utils import _normalize_to_list
from rhiza.models.template import GitHost


@dataclass
class TemplateLock:
    """Represents the structure of .rhiza/template.lock.

    Attributes:
        sha: The commit SHA of the last-synced template.
        repo: The template repository (e.g., "jebel-quant/rhiza").
        host: The git hosting platform (e.g., "github", "gitlab").
        ref: The branch or ref that was synced (e.g., "main").
        include: List of paths included from the template.
        exclude: List of paths excluded from the template.
        templates: List of template bundle names.
        files: List of file paths that were synced.
        synced_at: ISO 8601 UTC timestamp of when the sync was performed.
        strategy: The sync strategy used (e.g., "merge", "diff", "materialize").
    """

    sha: str
    repo: str = ""
    host: GitHost | str = GitHost.GITHUB
    ref: str = "main"
    include: list[str] = field(default_factory=list)
    exclude: list[str] = field(default_factory=list)
    templates: list[str] = field(default_factory=list)
    files: list[str] = field(default_factory=list)
    synced_at: str = ""
    strategy: str = ""

    @classmethod
    def from_yaml(cls, file_path: Path) -> "TemplateLock":
        """Load TemplateLock from a YAML file.

        Supports both the structured YAML format and the legacy plain-SHA format.

        Args:
            file_path: Path to the template.lock file.

        Returns:
            The loaded lock data.

        Raises:
            FileNotFoundError: If the file does not exist.
            yaml.YAMLError: If the YAML is malformed.
            ValueError: If the file format is not recognised.
        """
        with open(file_path, encoding="utf-8") as f:
            content = f.read()

        data = yaml.safe_load(content)

        # Legacy plain-SHA format: yaml.safe_load returns the SHA string directly.
        if isinstance(data, str):
            return cls(sha=data.strip())

        if not isinstance(data, dict):
            raise TypeError("Invalid template.lock format")  # noqa: TRY003

        return cls(
            sha=data.get("sha", ""),
            repo=data.get("repo", ""),
            host=data.get("host", GitHost.GITHUB),
            ref=data.get("ref", "main"),
            include=_normalize_to_list(data.get("include")),
            exclude=_normalize_to_list(data.get("exclude")),
            templates=_normalize_to_list(data.get("templates")),
            files=_normalize_to_list(data.get("files")),
            synced_at=data.get("synced_at", ""),
            strategy=data.get("strategy", ""),
        )

    def to_yaml(self, file_path: Path) -> None:
        """Save TemplateLock to a YAML file.

        Args:
            file_path: Path where the template.lock file should be saved.
        """
        file_path.parent.mkdir(parents=True, exist_ok=True)

        config: dict[str, Any] = {
            "sha": self.sha,
            "repo": self.repo,
            "host": str(self.host),
            "ref": self.ref,
            "include": self.include,
            "exclude": self.exclude,
            "templates": self.templates,
            "files": self.files,
        }

        if self.synced_at:
            config["synced_at"] = self.synced_at
        if self.strategy:
            config["strategy"] = self.strategy

        class _IndentedDumper(yaml.Dumper):
            def increase_indent(self, flow: bool = False, indentless: bool = False) -> None:
                # Always use indented style for sequences regardless of context.
                return super().increase_indent(flow, indentless=False)

        with open(file_path, "w", encoding="utf-8") as f:
            f.write("# This file is automatically generated by rhiza. Do not edit it manually.\n")
            yaml.dump(
                config,
                f,
                Dumper=_IndentedDumper,
                default_flow_style=False,
                sort_keys=False,
                explicit_start=True,
            )
